# Generated by Django 5.1.3 on 2024-12-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietBlog', '0001_initial'),
        ('diet_log', '0008_alter_meals_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_log.meals'),
        ),
    ]
