# Generated by Django 5.1.3 on 2024-11-26 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_log', '0002_remove_book_author_remove_book_genre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavMiles',
            new_name='FavMeals',
        ),
        migrations.RenameModel(
            old_name='Miles',
            new_name='Meals',
        ),
    ]
