# Generated by Django 5.1.3 on 2024-12-05 21:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_log', '0007_meals_file_delete_uploadedmealphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
